// Generated by JFlex 1.9.1 http://jflex.de/  (tweaked for IntelliJ platform)
// source: _SharpScriptLexer.flex

package net.servicestack.idea.sharpscript;

import com.intellij.psi.tree.IElementType;
import com.intellij.lexer.FlexLexer;
import com.intellij.util.containers.Stack;
import static com.intellij.psi.TokenType.BAD_CHARACTER;
import static com.intellij.psi.TokenType.WHITE_SPACE;
import static net.servicestack.idea.sharpscript.GeneratedTypes.*;

@SuppressWarnings ({"FieldCanBeLocal", "UnusedDeclaration", "WeakerAccess", "SameParameterValue", "CanBeFinal", "SameReturnValue", "RedundantThrows", "ConstantConditions"})

public class _SharpScriptLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int IN_OPEN_CLOSE = 2;
  public static final int IN_OPENBLOCK_CLOSEBLOCK = 4;
  public static final int IN_OPEN_RAW_BLOCK = 6;
  public static final int IN_OPEN_BLOCK_NAME = 8;
  public static final int IN_COMMENT = 10;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  3,  3,  4, 4
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\1\4"+
    "\1\5\1\6\3\0\1\7\1\10\1\11\1\12\2\0"+
    "\1\13\1\14\1\15\12\16\4\0\1\17\1\0\1\20"+
    "\21\21\1\22\10\21\1\23\1\24\1\25\1\26\1\27"+
    "\1\0\1\30\1\31\2\21\1\32\1\33\5\21\1\34"+
    "\1\21\1\35\3\21\1\36\1\37\1\40\1\41\5\21"+
    "\1\42\1\43\1\44\7\0\1\3\u01a2\0\2\3\326\0"+
    "\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\1\2\3\1\1\3\1\4\1\5\1\6"+
    "\3\7\3\1\2\10\1\11\2\0\1\12\3\0\2\7"+
    "\1\0\1\13\4\0\1\14\1\15\3\0\1\5\2\7"+
    "\4\0\1\16\1\17\1\20\1\0\1\21\2\0\1\22"+
    "\1\23\2\0\1\24\1\0\1\25\15\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[76];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\45\0\112\0\157\0\224\0\271\0\336\0\u0103"+
    "\0\u0128\0\u014d\0\u0172\0\271\0\u0197\0\271\0\u01bc\0\u01e1"+
    "\0\u0206\0\u022b\0\u0250\0\u0275\0\u029a\0\u02bf\0\u02e4\0\u0309"+
    "\0\u014d\0\271\0\u032e\0\u0353\0\u0378\0\u039d\0\u03c2\0\u03e7"+
    "\0\271\0\u040c\0\u0431\0\u0456\0\u047b\0\u04a0\0\271\0\u04c5"+
    "\0\u04ea\0\u050f\0\u0378\0\u0534\0\u0559\0\u057e\0\u05a3\0\u05c8"+
    "\0\u05ed\0\u04a0\0\271\0\271\0\u0612\0\u01bc\0\u0637\0\u065c"+
    "\0\271\0\271\0\u0681\0\u06a6\0\271\0\u06cb\0\271\0\u06f0"+
    "\0\u0715\0\u073a\0\u075f\0\u0784\0\u07a9\0\u07ce\0\u07f3\0\u0818"+
    "\0\u083d\0\u0862\0\u0887\0\u08ac";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[76];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\2\7\37\6\1\10\1\6\1\11\7\6\1\12"+
    "\1\13\1\14\4\6\1\15\1\6\1\16\2\17\4\6"+
    "\4\17\1\20\4\17\1\21\1\17\1\22\1\6\1\23"+
    "\7\6\1\12\1\13\1\14\4\6\1\15\1\6\1\16"+
    "\2\17\4\6\4\17\1\20\4\17\1\21\1\17\1\24"+
    "\47\6\2\25\2\6\7\25\1\26\31\25\46\0\2\7"+
    "\104\0\1\27\46\0\1\30\7\31\1\32\12\31\1\0"+
    "\1\31\1\33\20\31\24\0\1\34\34\0\1\35\1\0"+
    "\1\15\44\0\1\17\2\0\2\17\4\0\13\17\21\0"+
    "\1\17\2\0\2\17\4\0\1\17\1\36\11\17\21\0"+
    "\1\17\2\0\2\17\4\0\7\17\1\37\3\17\45\0"+
    "\1\40\46\0\1\41\42\0\1\42\15\0\1\43\44\0"+
    "\1\44\35\0\1\45\1\0\1\46\10\0\1\47\22\0"+
    "\1\50\46\0\1\51\7\0\1\31\14\0\1\31\4\0"+
    "\1\31\1\0\1\31\1\0\2\31\1\0\1\31\27\0"+
    "\1\52\37\0\1\53\44\0\1\17\2\0\2\17\4\0"+
    "\5\17\1\54\5\17\21\0\1\17\2\0\2\17\4\0"+
    "\12\17\1\55\7\0\1\45\44\0\1\45\10\0\1\56"+
    "\42\0\1\57\44\0\1\57\30\0\1\60\13\0\1\61"+
    "\47\0\1\62\2\0\2\62\5\0\12\62\45\0\1\63"+
    "\46\0\1\64\5\0\1\65\55\0\1\17\2\0\2\17"+
    "\4\0\10\17\1\55\2\17\21\0\1\17\2\0\2\17"+
    "\4\0\3\17\1\66\7\17\21\0\1\67\2\0\2\67"+
    "\5\0\12\67\47\0\1\70\44\0\1\71\13\0\1\72"+
    "\55\0\1\73\36\0\1\67\2\0\2\67\5\0\12\67"+
    "\2\0\1\74\44\0\1\75\31\0\1\76\57\0\1\77"+
    "\40\0\1\100\41\0\1\101\42\0\1\102\47\0\1\103"+
    "\33\0\1\104\62\0\1\105\24\0\1\106\47\0\1\107"+
    "\23\0\1\110\63\0\1\111\42\0\1\112\47\0\1\113"+
    "\30\0\1\114\45\0\1\32\32\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[2257];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\1\11\5\1\1\11\1\1\1\11\11\1\2\0"+
    "\1\11\3\0\2\1\1\0\1\11\4\0\1\1\1\11"+
    "\3\0\3\1\4\0\1\1\2\11\1\0\1\1\2\0"+
    "\2\11\2\0\1\11\1\0\1\11\15\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[76];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
  public _SharpScriptLexer() {
    this((java.io.Reader)null);
  }

  private Stack<Integer> stack = new Stack<>();
  private Stack<String> blockStack = new Stack<>();

  public void yypushState(int newState) {
    stack.push(yystate());
    yybegin(newState);
  }

  public void yypopState() {
    yybegin(stack.pop());
  }

  String blockName;  // to store the block name like 'if', 'each', etc.



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _SharpScriptLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return BAD_CHARACTER;
            }
          // fall through
          case 22: break;
          case 2:
            { return WHITE_SPACE;
            }
          // fall through
          case 23: break;
          case 3:
            { return OPEN_SEXPR;
            }
          // fall through
          case 24: break;
          case 4:
            { return CLOSE_SEXPR;
            }
          // fall through
          case 25: break;
          case 5:
            { return NUMBER;
            }
          // fall through
          case 26: break;
          case 6:
            { return DATA_PREFIX;
            }
          // fall through
          case 27: break;
          case 7:
            { return ID;
            }
          // fall through
          case 28: break;
          case 8:
            { return COMMENT_CONTENT;
            }
          // fall through
          case 29: break;
          case 9:
            { yybegin(IN_OPEN_CLOSE); return OPEN;
            }
          // fall through
          case 30: break;
          case 10:
            { return STRING;
            }
          // fall through
          case 31: break;
          case 11:
            { yybegin(YYINITIAL); return CLOSE;
            }
          // fall through
          case 32: break;
          case 12:
            { yybegin(IN_OPEN_BLOCK_NAME); return OPEN_BLOCK;
            }
          // fall through
          case 33: break;
          case 13:
            { return OPEN_PARTIAL;
            }
          // fall through
          case 34: break;
          case 14:
            { String blockName = yytext().toString().substring(3); // Extract block name
      blockStack.push(blockName);  // Push block name onto stack
      yybegin(IN_OPENBLOCK_CLOSEBLOCK);
      return OPEN_BLOCK;
            }
          // fall through
          case 35: break;
          case 15:
            { return OPEN_RAW_BLOCK;
            }
          // fall through
          case 36: break;
          case 16:
            { return CLOSE_RAW_BLOCK;
            }
          // fall through
          case 37: break;
          case 17:
            { return BOOLEAN;
            }
          // fall through
          case 38: break;
          case 18:
            { yybegin(YYINITIAL); return COMMENT_CLOSE;
            }
          // fall through
          case 39: break;
          case 19:
            { yybegin(IN_COMMENT); return COMMENT_OPEN;
            }
          // fall through
          case 40: break;
          case 20:
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, 1);
            { /* do nothing, as COMMENT_CLOSE is upcoming */
            }
          // fall through
          case 41: break;
          case 21:
            { String closeName = yytext().toString().substring(3, yytext().length() - 2);  // Extract block name from closing tag
        if (!blockStack.isEmpty() && closeName.equals(blockStack.peek())) {  // Check if it matches the last opened block
          blockStack.pop();  // Pop the last opened block
          yybegin(YYINITIAL);
          return CLOSE_BLOCK;
        }
        // Handle unmatched blocks here (optional)
            }
          // fall through
          case 42: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
